In [79]:
import pandas as pd

In [80]:
trips = pd.read_parquet('green_tripdata_2025-11.parquet')
zones = pd.read_csv('taxi_zone_lookup.csv')

In [81]:
trips.head(1)
# trips.shape

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.0,0.0

In [83]:
zones.head(1)

   LocationID Borough            Zone service_zone
0           1     EWR  Newark Airport          EWR

In [84]:
""" For the trips in November 2025 (lpep_pickup_datetime between '2025-11-01' and '2025-12-01', exclusive of the upper bound), 
how many trips had a trip_distance of LESS than or equal to 1 mile?
"""
OneMiletrips = len(trips.query('trip_distance <= 1'))
print(f'Answer 3, One mile trips count: {OneMiletrips}')

Answer 3, One mile trips count: 8009

In [90]:
""" Which was the pick up day with the longest trip distance?
Only consider trips with trip_distance less than 100 miles (to exclude data errors).
"""
longTrip = trips.query('trip_distance < 100').sort_values(by='trip_distance', ascending=False)
# longTrip.head(1)
distance = longTrip['trip_distance'].iloc[0]
answer4 = longTrip['lpep_pickup_datetime'].iloc[0]
print(f'Answer 4, pickup day with longest trip distance: "{answer4}" with a {distance} Miles of distance')

Answer 4, pickup day with longest trip distance: "2025-11-14 15:36:27" with a 88.03 Miles of distance

In [92]:

""" Which was the pickup zone with the largest total_amount (sum of all trips) on November 18th, 2025?
"""
joindata = trips.merge(zones, left_on='PULocationID' , right_on='LocationID', how='left')
largestamount = joindata.groupby('Zone')['total_amount'].sum().reset_index().sort_values(by='total_amount', ascending=False)
# largestamount.head(1)
answer5 = largestamount['Zone'].iloc[0]
amount = largestamount['total_amount'].iloc[0]
print(f'Answer 5, pickup day with longest tripdistance: {answer5} , with sum  of ${amount}')

Answer 5, pickup day with longest tripdistance: East Harlem North , with sum  of $257684.7

In [93]:
""" For the passengers picked up in the zone named "East Harlem North" in November 2025, 
which was the drop off zone that had the largest tip?

Note: it's tip , not trip. We need the name of the zone, not the ID.
"""
bigtip = joindata.query('PULocationID == 74').sort_values(by='tip_amount', ascending=False)
tipamount = bigtip['tip_amount'].iloc[0]
# bigtip[['PULocationID','tip_amount','DOLocationID']].head(1)
### Get DOLocationID
dropID = bigtip['DOLocationID'].iloc[0]
### Get Zone
zone = zones.query('LocationID == @dropID')
### Get column value
dropOffzone = zone['Zone'].iloc[0]
print(f'Dropoff zone with the lasrgest tip: "{dropOffzone}" with tip amount: ${tipamount}')

Dropoff zone with the lasrgest tip: "Yorkville West" with tip amount: $81.89